
package jaxb.restaurant.response;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.6
 * 2013-08-11T23:34:10.483-06:00
 * Generated source version: 2.7.6
 */

@WebFault(name = "IOException", targetNamespace = "http://Servlet/")
public class IOException_Exception extends Exception {
    
    private jaxb.restaurant.response.IOException ioException;

    public IOException_Exception() {
        super();
    }
    
    public IOException_Exception(String message) {
        super(message);
    }
    
    public IOException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public IOException_Exception(String message, jaxb.restaurant.response.IOException ioException) {
        super(message);
        this.ioException = ioException;
    }

    public IOException_Exception(String message, jaxb.restaurant.response.IOException ioException, Throwable cause) {
        super(message, cause);
        this.ioException = ioException;
    }

    public jaxb.restaurant.response.IOException getFaultInfo() {
        return this.ioException;
    }
}
