
package jaxb.restaurant.response;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.6
 * 2013-08-11T23:34:10.477-06:00
 * Generated source version: 2.7.6
 */

@WebFault(name = "ServletException", targetNamespace = "http://Servlet/")
public class ServletException_Exception extends Exception {
    
    private jaxb.restaurant.response.ServletException servletException;

    public ServletException_Exception() {
        super();
    }
    
    public ServletException_Exception(String message) {
        super(message);
    }
    
    public ServletException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public ServletException_Exception(String message, jaxb.restaurant.response.ServletException servletException) {
        super(message);
        this.servletException = servletException;
    }

    public ServletException_Exception(String message, jaxb.restaurant.response.ServletException servletException, Throwable cause) {
        super(message, cause);
        this.servletException = servletException;
    }

    public jaxb.restaurant.response.ServletException getFaultInfo() {
        return this.servletException;
    }
}
