package jaxb.restaurant.response;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2013-08-11T23:34:10.497-06:00
 * Generated source version: 2.7.6
 * 
 */
@WebServiceClient(name = "ZipCodeServlet", 
                  wsdlLocation = "file:/C:/Users/tpettry/Documents/Java3/Pettry_Travis_CSC380/first_distributed_system/jaxws_exersicse/src/jaxb/restaurant/response/ZipCodeServlet.wsdl",
                  targetNamespace = "http://Servlet/") 
public class ZipCodeServlet extends javax.xml.ws.Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://Servlet/", "ZipCodeServlet");
    public final static QName ZipCodeServletPort = new QName("http://Servlet/", "ZipCodeServletPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/tpettry/Documents/Java3/Pettry_Travis_CSC380/first_distributed_system/jaxws_exersicse/src/jaxb/restaurant/response/ZipCodeServlet.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ZipCodeServlet.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/tpettry/Documents/Java3/Pettry_Travis_CSC380/first_distributed_system/jaxws_exersicse/src/jaxb/restaurant/response/ZipCodeServlet.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ZipCodeServlet(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ZipCodeServlet(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ZipCodeServlet() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ZipCodeServlet(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ZipCodeServlet(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ZipCodeServlet(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ZipCodeServletPortType
     */
    @WebEndpoint(name = "ZipCodeServletPort")
    public ZipCodeServletPortType getZipCodeServletPort() {
        return super.getPort(ZipCodeServletPort, ZipCodeServletPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZipCodeServletPortType
     */
    @WebEndpoint(name = "ZipCodeServletPort")
    public ZipCodeServletPortType getZipCodeServletPort(WebServiceFeature... features) {
        return super.getPort(ZipCodeServletPort, ZipCodeServletPortType.class, features);
    }

}
