package jaxb.restaurant.response;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2013-08-11T23:34:10.488-06:00
 * Generated source version: 2.7.6
 * 
 */
@WebService(targetNamespace = "http://Servlet/", name = "ZipCodeServletPortType")
@XmlSeeAlso({ObjectFactory.class})
public interface ZipCodeServletPortType {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getServletInfo", targetNamespace = "http://Servlet/", className = "jaxb.restaurant.response.GetServletInfo")
    @WebMethod
    @ResponseWrapper(localName = "getServletInfoResponse", targetNamespace = "http://Servlet/", className = "jaxb.restaurant.response.GetServletInfoResponse")
    public java.lang.String getServletInfo();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getBus", targetNamespace = "http://Servlet/", className = "jaxb.restaurant.response.GetBus")
    @WebMethod
    @ResponseWrapper(localName = "getBusResponse", targetNamespace = "http://Servlet/", className = "jaxb.restaurant.response.GetBusResponse")
    public java.lang.Object getBus();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getServletContext", targetNamespace = "http://Servlet/", className = "jaxb.restaurant.response.GetServletContext")
    @WebMethod
    @ResponseWrapper(localName = "getServletContextResponse", targetNamespace = "http://Servlet/", className = "jaxb.restaurant.response.GetServletContextResponse")
    public java.lang.Object getServletContext();

    @RequestWrapper(localName = "init1", targetNamespace = "http://Servlet/", className = "jaxb.restaurant.response.Init1")
    @WebMethod
    @ResponseWrapper(localName = "init1Response", targetNamespace = "http://Servlet/", className = "jaxb.restaurant.response.Init1Response")
    public void init1(
        @WebParam(name = "filterConfig", targetNamespace = "")
        java.lang.Object filterConfig
    ) throws ServletException_Exception;

    @RequestWrapper(localName = "init", targetNamespace = "http://Servlet/", className = "jaxb.restaurant.response.Init")
    @WebMethod
    @ResponseWrapper(localName = "initResponse", targetNamespace = "http://Servlet/", className = "jaxb.restaurant.response.InitResponse")
    public void init() throws ServletException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getServletName", targetNamespace = "http://Servlet/", className = "jaxb.restaurant.response.GetServletName")
    @WebMethod
    @ResponseWrapper(localName = "getServletNameResponse", targetNamespace = "http://Servlet/", className = "jaxb.restaurant.response.GetServletNameResponse")
    public java.lang.String getServletName();

    @RequestWrapper(localName = "init2", targetNamespace = "http://Servlet/", className = "jaxb.restaurant.response.Init2")
    @WebMethod
    @ResponseWrapper(localName = "init2Response", targetNamespace = "http://Servlet/", className = "jaxb.restaurant.response.Init2Response")
    public void init2(
        @WebParam(name = "sc", targetNamespace = "")
        java.lang.Object sc
    ) throws ServletException_Exception;

    @RequestWrapper(localName = "setBus", targetNamespace = "http://Servlet/", className = "jaxb.restaurant.response.SetBus")
    @WebMethod
    @ResponseWrapper(localName = "setBusResponse", targetNamespace = "http://Servlet/", className = "jaxb.restaurant.response.SetBusResponse")
    public void setBus(
        @WebParam(name = "bus", targetNamespace = "")
        java.lang.Object bus
    );

    @RequestWrapper(localName = "log1", targetNamespace = "http://Servlet/", className = "jaxb.restaurant.response.Log1")
    @WebMethod
    @ResponseWrapper(localName = "log1Response", targetNamespace = "http://Servlet/", className = "jaxb.restaurant.response.Log1Response")
    public void log1(
        @WebParam(name = "message", targetNamespace = "")
        java.lang.String message,
        @WebParam(name = "t", targetNamespace = "")
        java.lang.Object t
    );

    @RequestWrapper(localName = "service", targetNamespace = "http://Servlet/", className = "jaxb.restaurant.response.Service")
    @WebMethod
    @ResponseWrapper(localName = "serviceResponse", targetNamespace = "http://Servlet/", className = "jaxb.restaurant.response.ServiceResponse")
    public void service(
        @WebParam(name = "req", targetNamespace = "")
        java.lang.Object req,
        @WebParam(name = "res", targetNamespace = "")
        java.lang.Object res
    ) throws IOException_Exception, ServletException_Exception;

    @RequestWrapper(localName = "destroyBus", targetNamespace = "http://Servlet/", className = "jaxb.restaurant.response.DestroyBus")
    @WebMethod
    @ResponseWrapper(localName = "destroyBusResponse", targetNamespace = "http://Servlet/", className = "jaxb.restaurant.response.DestroyBusResponse")
    public void destroyBus();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getInitParameter", targetNamespace = "http://Servlet/", className = "jaxb.restaurant.response.GetInitParameter")
    @WebMethod
    @ResponseWrapper(localName = "getInitParameterResponse", targetNamespace = "http://Servlet/", className = "jaxb.restaurant.response.GetInitParameterResponse")
    public java.lang.String getInitParameter(
        @WebParam(name = "name", targetNamespace = "")
        java.lang.String name
    );

    @RequestWrapper(localName = "log", targetNamespace = "http://Servlet/", className = "jaxb.restaurant.response.Log")
    @WebMethod
    @ResponseWrapper(localName = "logResponse", targetNamespace = "http://Servlet/", className = "jaxb.restaurant.response.LogResponse")
    public void log(
        @WebParam(name = "msg", targetNamespace = "")
        java.lang.String msg
    );

    @RequestWrapper(localName = "doFilter", targetNamespace = "http://Servlet/", className = "jaxb.restaurant.response.DoFilter")
    @WebMethod
    @ResponseWrapper(localName = "doFilterResponse", targetNamespace = "http://Servlet/", className = "jaxb.restaurant.response.DoFilterResponse")
    public void doFilter(
        @WebParam(name = "request", targetNamespace = "")
        java.lang.Object request,
        @WebParam(name = "response", targetNamespace = "")
        java.lang.Object response,
        @WebParam(name = "chain", targetNamespace = "")
        java.lang.Object chain
    ) throws IOException_Exception, ServletException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getInitParameterNames", targetNamespace = "http://Servlet/", className = "jaxb.restaurant.response.GetInitParameterNames")
    @WebMethod
    @ResponseWrapper(localName = "getInitParameterNamesResponse", targetNamespace = "http://Servlet/", className = "jaxb.restaurant.response.GetInitParameterNamesResponse")
    public java.lang.Object getInitParameterNames();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getServletConfig", targetNamespace = "http://Servlet/", className = "jaxb.restaurant.response.GetServletConfig")
    @WebMethod
    @ResponseWrapper(localName = "getServletConfigResponse", targetNamespace = "http://Servlet/", className = "jaxb.restaurant.response.GetServletConfigResponse")
    public java.lang.Object getServletConfig();

    @RequestWrapper(localName = "destroy", targetNamespace = "http://Servlet/", className = "jaxb.restaurant.response.Destroy")
    @WebMethod
    @ResponseWrapper(localName = "destroyResponse", targetNamespace = "http://Servlet/", className = "jaxb.restaurant.response.DestroyResponse")
    public void destroy();
}
