//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=4.0.30319.1.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="ZipCodeServletSoapBinding", Namespace="http://Servlet/")]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(destroyResponse))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(destroy))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(doFilterResponse))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(doFilter))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(getInitParameterNamesResponse))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(getInitParameterNames))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(getServletConfigResponse))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(getServletConfig))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(logResponse))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(log))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(getInitParameterResponse))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(getInitParameter))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(destroyBusResponse))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(destroyBus))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(serviceResponse))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(service))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(log1Response))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(log1))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(init2Response))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(init2))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(setBusResponse))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(setBus))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(getServletNameResponse))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(getServletName))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(initResponse))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(init))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(init1Response))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(init1))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(getServletContextResponse))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(getServletContext))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(getBusResponse))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(getBus))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(getServletInfoResponse))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(getServletInfo))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(IOException))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ServletException))]
public partial class ZipCodeServlet : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback getServletInfoOperationCompleted;
    
    private System.Threading.SendOrPostCallback getBusOperationCompleted;
    
    private System.Threading.SendOrPostCallback getServletContextOperationCompleted;
    
    private System.Threading.SendOrPostCallback init1OperationCompleted;
    
    private System.Threading.SendOrPostCallback initOperationCompleted;
    
    private System.Threading.SendOrPostCallback getServletNameOperationCompleted;
    
    private System.Threading.SendOrPostCallback setBusOperationCompleted;
    
    private System.Threading.SendOrPostCallback init2OperationCompleted;
    
    private System.Threading.SendOrPostCallback log1OperationCompleted;
    
    private System.Threading.SendOrPostCallback serviceOperationCompleted;
    
    private System.Threading.SendOrPostCallback destroyBusOperationCompleted;
    
    private System.Threading.SendOrPostCallback getInitParameterOperationCompleted;
    
    private System.Threading.SendOrPostCallback logOperationCompleted;
    
    private System.Threading.SendOrPostCallback getServletConfigOperationCompleted;
    
    private System.Threading.SendOrPostCallback getInitParameterNamesOperationCompleted;
    
    private System.Threading.SendOrPostCallback doFilterOperationCompleted;
    
    private System.Threading.SendOrPostCallback destroyOperationCompleted;
    
    /// <remarks/>
    public ZipCodeServlet() {
        this.Url = "http://localhost:9090/ZipCodeServletPort";
    }
    
    /// <remarks/>
    public event getServletInfoCompletedEventHandler getServletInfoCompleted;
    
    /// <remarks/>
    public event getBusCompletedEventHandler getBusCompleted;
    
    /// <remarks/>
    public event getServletContextCompletedEventHandler getServletContextCompleted;
    
    /// <remarks/>
    public event init1CompletedEventHandler init1Completed;
    
    /// <remarks/>
    public event initCompletedEventHandler initCompleted;
    
    /// <remarks/>
    public event getServletNameCompletedEventHandler getServletNameCompleted;
    
    /// <remarks/>
    public event setBusCompletedEventHandler setBusCompleted;
    
    /// <remarks/>
    public event init2CompletedEventHandler init2Completed;
    
    /// <remarks/>
    public event log1CompletedEventHandler log1Completed;
    
    /// <remarks/>
    public event serviceCompletedEventHandler serviceCompleted;
    
    /// <remarks/>
    public event destroyBusCompletedEventHandler destroyBusCompleted;
    
    /// <remarks/>
    public event getInitParameterCompletedEventHandler getInitParameterCompleted;
    
    /// <remarks/>
    public event logCompletedEventHandler logCompleted;
    
    /// <remarks/>
    public event getServletConfigCompletedEventHandler getServletConfigCompleted;
    
    /// <remarks/>
    public event getInitParameterNamesCompletedEventHandler getInitParameterNamesCompleted;
    
    /// <remarks/>
    public event doFilterCompletedEventHandler doFilterCompleted;
    
    /// <remarks/>
    public event destroyCompletedEventHandler destroyCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://Servlet/", ResponseNamespace="http://Servlet/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string getServletInfo() {
        object[] results = this.Invoke("getServletInfo", new object[0]);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegingetServletInfo(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getServletInfo", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public string EndgetServletInfo(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void getServletInfoAsync() {
        this.getServletInfoAsync(null);
    }
    
    /// <remarks/>
    public void getServletInfoAsync(object userState) {
        if ((this.getServletInfoOperationCompleted == null)) {
            this.getServletInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetServletInfoOperationCompleted);
        }
        this.InvokeAsync("getServletInfo", new object[0], this.getServletInfoOperationCompleted, userState);
    }
    
    private void OngetServletInfoOperationCompleted(object arg) {
        if ((this.getServletInfoCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.getServletInfoCompleted(this, new getServletInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://Servlet/", ResponseNamespace="http://Servlet/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public object getBus() {
        object[] results = this.Invoke("getBus", new object[0]);
        return ((object)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegingetBus(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getBus", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public object EndgetBus(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((object)(results[0]));
    }
    
    /// <remarks/>
    public void getBusAsync() {
        this.getBusAsync(null);
    }
    
    /// <remarks/>
    public void getBusAsync(object userState) {
        if ((this.getBusOperationCompleted == null)) {
            this.getBusOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetBusOperationCompleted);
        }
        this.InvokeAsync("getBus", new object[0], this.getBusOperationCompleted, userState);
    }
    
    private void OngetBusOperationCompleted(object arg) {
        if ((this.getBusCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.getBusCompleted(this, new getBusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://Servlet/", ResponseNamespace="http://Servlet/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public object getServletContext() {
        object[] results = this.Invoke("getServletContext", new object[0]);
        return ((object)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegingetServletContext(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getServletContext", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public object EndgetServletContext(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((object)(results[0]));
    }
    
    /// <remarks/>
    public void getServletContextAsync() {
        this.getServletContextAsync(null);
    }
    
    /// <remarks/>
    public void getServletContextAsync(object userState) {
        if ((this.getServletContextOperationCompleted == null)) {
            this.getServletContextOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetServletContextOperationCompleted);
        }
        this.InvokeAsync("getServletContext", new object[0], this.getServletContextOperationCompleted, userState);
    }
    
    private void OngetServletContextOperationCompleted(object arg) {
        if ((this.getServletContextCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.getServletContextCompleted(this, new getServletContextCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://Servlet/", ResponseNamespace="http://Servlet/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void init1([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] object filterConfig) {
        this.Invoke("init1", new object[] {
                    filterConfig});
    }
    
    /// <remarks/>
    public System.IAsyncResult Begininit1(object filterConfig, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("init1", new object[] {
                    filterConfig}, callback, asyncState);
    }
    
    /// <remarks/>
    public void Endinit1(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    public void init1Async(object filterConfig) {
        this.init1Async(filterConfig, null);
    }
    
    /// <remarks/>
    public void init1Async(object filterConfig, object userState) {
        if ((this.init1OperationCompleted == null)) {
            this.init1OperationCompleted = new System.Threading.SendOrPostCallback(this.Oninit1OperationCompleted);
        }
        this.InvokeAsync("init1", new object[] {
                    filterConfig}, this.init1OperationCompleted, userState);
    }
    
    private void Oninit1OperationCompleted(object arg) {
        if ((this.init1Completed != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.init1Completed(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://Servlet/", ResponseNamespace="http://Servlet/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void init() {
        this.Invoke("init", new object[0]);
    }
    
    /// <remarks/>
    public System.IAsyncResult Begininit(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("init", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public void Endinit(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    public void initAsync() {
        this.initAsync(null);
    }
    
    /// <remarks/>
    public void initAsync(object userState) {
        if ((this.initOperationCompleted == null)) {
            this.initOperationCompleted = new System.Threading.SendOrPostCallback(this.OninitOperationCompleted);
        }
        this.InvokeAsync("init", new object[0], this.initOperationCompleted, userState);
    }
    
    private void OninitOperationCompleted(object arg) {
        if ((this.initCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.initCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://Servlet/", ResponseNamespace="http://Servlet/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string getServletName() {
        object[] results = this.Invoke("getServletName", new object[0]);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegingetServletName(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getServletName", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public string EndgetServletName(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void getServletNameAsync() {
        this.getServletNameAsync(null);
    }
    
    /// <remarks/>
    public void getServletNameAsync(object userState) {
        if ((this.getServletNameOperationCompleted == null)) {
            this.getServletNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetServletNameOperationCompleted);
        }
        this.InvokeAsync("getServletName", new object[0], this.getServletNameOperationCompleted, userState);
    }
    
    private void OngetServletNameOperationCompleted(object arg) {
        if ((this.getServletNameCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.getServletNameCompleted(this, new getServletNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://Servlet/", ResponseNamespace="http://Servlet/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void setBus([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] object bus) {
        this.Invoke("setBus", new object[] {
                    bus});
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginsetBus(object bus, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("setBus", new object[] {
                    bus}, callback, asyncState);
    }
    
    /// <remarks/>
    public void EndsetBus(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    public void setBusAsync(object bus) {
        this.setBusAsync(bus, null);
    }
    
    /// <remarks/>
    public void setBusAsync(object bus, object userState) {
        if ((this.setBusOperationCompleted == null)) {
            this.setBusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsetBusOperationCompleted);
        }
        this.InvokeAsync("setBus", new object[] {
                    bus}, this.setBusOperationCompleted, userState);
    }
    
    private void OnsetBusOperationCompleted(object arg) {
        if ((this.setBusCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.setBusCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://Servlet/", ResponseNamespace="http://Servlet/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void init2([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] object sc) {
        this.Invoke("init2", new object[] {
                    sc});
    }
    
    /// <remarks/>
    public System.IAsyncResult Begininit2(object sc, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("init2", new object[] {
                    sc}, callback, asyncState);
    }
    
    /// <remarks/>
    public void Endinit2(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    public void init2Async(object sc) {
        this.init2Async(sc, null);
    }
    
    /// <remarks/>
    public void init2Async(object sc, object userState) {
        if ((this.init2OperationCompleted == null)) {
            this.init2OperationCompleted = new System.Threading.SendOrPostCallback(this.Oninit2OperationCompleted);
        }
        this.InvokeAsync("init2", new object[] {
                    sc}, this.init2OperationCompleted, userState);
    }
    
    private void Oninit2OperationCompleted(object arg) {
        if ((this.init2Completed != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.init2Completed(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://Servlet/", ResponseNamespace="http://Servlet/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void log1([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string message, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] object t) {
        this.Invoke("log1", new object[] {
                    message,
                    t});
    }
    
    /// <remarks/>
    public System.IAsyncResult Beginlog1(string message, object t, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("log1", new object[] {
                    message,
                    t}, callback, asyncState);
    }
    
    /// <remarks/>
    public void Endlog1(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    public void log1Async(string message, object t) {
        this.log1Async(message, t, null);
    }
    
    /// <remarks/>
    public void log1Async(string message, object t, object userState) {
        if ((this.log1OperationCompleted == null)) {
            this.log1OperationCompleted = new System.Threading.SendOrPostCallback(this.Onlog1OperationCompleted);
        }
        this.InvokeAsync("log1", new object[] {
                    message,
                    t}, this.log1OperationCompleted, userState);
    }
    
    private void Onlog1OperationCompleted(object arg) {
        if ((this.log1Completed != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.log1Completed(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://Servlet/", ResponseNamespace="http://Servlet/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void service([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] object req, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] object res) {
        this.Invoke("service", new object[] {
                    req,
                    res});
    }
    
    /// <remarks/>
    public System.IAsyncResult Beginservice(object req, object res, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("service", new object[] {
                    req,
                    res}, callback, asyncState);
    }
    
    /// <remarks/>
    public void Endservice(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    public void serviceAsync(object req, object res) {
        this.serviceAsync(req, res, null);
    }
    
    /// <remarks/>
    public void serviceAsync(object req, object res, object userState) {
        if ((this.serviceOperationCompleted == null)) {
            this.serviceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnserviceOperationCompleted);
        }
        this.InvokeAsync("service", new object[] {
                    req,
                    res}, this.serviceOperationCompleted, userState);
    }
    
    private void OnserviceOperationCompleted(object arg) {
        if ((this.serviceCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.serviceCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://Servlet/", ResponseNamespace="http://Servlet/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void destroyBus() {
        this.Invoke("destroyBus", new object[0]);
    }
    
    /// <remarks/>
    public System.IAsyncResult BegindestroyBus(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("destroyBus", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public void EnddestroyBus(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    public void destroyBusAsync() {
        this.destroyBusAsync(null);
    }
    
    /// <remarks/>
    public void destroyBusAsync(object userState) {
        if ((this.destroyBusOperationCompleted == null)) {
            this.destroyBusOperationCompleted = new System.Threading.SendOrPostCallback(this.OndestroyBusOperationCompleted);
        }
        this.InvokeAsync("destroyBus", new object[0], this.destroyBusOperationCompleted, userState);
    }
    
    private void OndestroyBusOperationCompleted(object arg) {
        if ((this.destroyBusCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.destroyBusCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://Servlet/", ResponseNamespace="http://Servlet/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string getInitParameter([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string name) {
        object[] results = this.Invoke("getInitParameter", new object[] {
                    name});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegingetInitParameter(string name, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getInitParameter", new object[] {
                    name}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndgetInitParameter(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void getInitParameterAsync(string name) {
        this.getInitParameterAsync(name, null);
    }
    
    /// <remarks/>
    public void getInitParameterAsync(string name, object userState) {
        if ((this.getInitParameterOperationCompleted == null)) {
            this.getInitParameterOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetInitParameterOperationCompleted);
        }
        this.InvokeAsync("getInitParameter", new object[] {
                    name}, this.getInitParameterOperationCompleted, userState);
    }
    
    private void OngetInitParameterOperationCompleted(object arg) {
        if ((this.getInitParameterCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.getInitParameterCompleted(this, new getInitParameterCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://Servlet/", ResponseNamespace="http://Servlet/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void log([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string msg) {
        this.Invoke("log", new object[] {
                    msg});
    }
    
    /// <remarks/>
    public System.IAsyncResult Beginlog(string msg, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("log", new object[] {
                    msg}, callback, asyncState);
    }
    
    /// <remarks/>
    public void Endlog(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    public void logAsync(string msg) {
        this.logAsync(msg, null);
    }
    
    /// <remarks/>
    public void logAsync(string msg, object userState) {
        if ((this.logOperationCompleted == null)) {
            this.logOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlogOperationCompleted);
        }
        this.InvokeAsync("log", new object[] {
                    msg}, this.logOperationCompleted, userState);
    }
    
    private void OnlogOperationCompleted(object arg) {
        if ((this.logCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.logCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://Servlet/", ResponseNamespace="http://Servlet/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public object getServletConfig() {
        object[] results = this.Invoke("getServletConfig", new object[0]);
        return ((object)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegingetServletConfig(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getServletConfig", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public object EndgetServletConfig(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((object)(results[0]));
    }
    
    /// <remarks/>
    public void getServletConfigAsync() {
        this.getServletConfigAsync(null);
    }
    
    /// <remarks/>
    public void getServletConfigAsync(object userState) {
        if ((this.getServletConfigOperationCompleted == null)) {
            this.getServletConfigOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetServletConfigOperationCompleted);
        }
        this.InvokeAsync("getServletConfig", new object[0], this.getServletConfigOperationCompleted, userState);
    }
    
    private void OngetServletConfigOperationCompleted(object arg) {
        if ((this.getServletConfigCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.getServletConfigCompleted(this, new getServletConfigCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://Servlet/", ResponseNamespace="http://Servlet/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public object getInitParameterNames() {
        object[] results = this.Invoke("getInitParameterNames", new object[0]);
        return ((object)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegingetInitParameterNames(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getInitParameterNames", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public object EndgetInitParameterNames(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((object)(results[0]));
    }
    
    /// <remarks/>
    public void getInitParameterNamesAsync() {
        this.getInitParameterNamesAsync(null);
    }
    
    /// <remarks/>
    public void getInitParameterNamesAsync(object userState) {
        if ((this.getInitParameterNamesOperationCompleted == null)) {
            this.getInitParameterNamesOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetInitParameterNamesOperationCompleted);
        }
        this.InvokeAsync("getInitParameterNames", new object[0], this.getInitParameterNamesOperationCompleted, userState);
    }
    
    private void OngetInitParameterNamesOperationCompleted(object arg) {
        if ((this.getInitParameterNamesCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.getInitParameterNamesCompleted(this, new getInitParameterNamesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://Servlet/", ResponseNamespace="http://Servlet/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void doFilter([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] object request, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] object response, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] object chain) {
        this.Invoke("doFilter", new object[] {
                    request,
                    response,
                    chain});
    }
    
    /// <remarks/>
    public System.IAsyncResult BegindoFilter(object request, object response, object chain, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("doFilter", new object[] {
                    request,
                    response,
                    chain}, callback, asyncState);
    }
    
    /// <remarks/>
    public void EnddoFilter(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    public void doFilterAsync(object request, object response, object chain) {
        this.doFilterAsync(request, response, chain, null);
    }
    
    /// <remarks/>
    public void doFilterAsync(object request, object response, object chain, object userState) {
        if ((this.doFilterOperationCompleted == null)) {
            this.doFilterOperationCompleted = new System.Threading.SendOrPostCallback(this.OndoFilterOperationCompleted);
        }
        this.InvokeAsync("doFilter", new object[] {
                    request,
                    response,
                    chain}, this.doFilterOperationCompleted, userState);
    }
    
    private void OndoFilterOperationCompleted(object arg) {
        if ((this.doFilterCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.doFilterCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://Servlet/", ResponseNamespace="http://Servlet/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void destroy() {
        this.Invoke("destroy", new object[0]);
    }
    
    /// <remarks/>
    public System.IAsyncResult Begindestroy(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("destroy", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public void Enddestroy(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    public void destroyAsync() {
        this.destroyAsync(null);
    }
    
    /// <remarks/>
    public void destroyAsync(object userState) {
        if ((this.destroyOperationCompleted == null)) {
            this.destroyOperationCompleted = new System.Threading.SendOrPostCallback(this.OndestroyOperationCompleted);
        }
        this.InvokeAsync("destroy", new object[0], this.destroyOperationCompleted, userState);
    }
    
    private void OndestroyOperationCompleted(object arg) {
        if ((this.destroyCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.destroyCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Servlet/")]
public partial class destroyResponse {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Servlet/")]
public partial class destroy {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Servlet/")]
public partial class doFilterResponse {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Servlet/")]
public partial class doFilter {
    
    private object requestField;
    
    private object responseField;
    
    private object chainField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public object request {
        get {
            return this.requestField;
        }
        set {
            this.requestField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public object response {
        get {
            return this.responseField;
        }
        set {
            this.responseField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public object chain {
        get {
            return this.chainField;
        }
        set {
            this.chainField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Servlet/")]
public partial class getInitParameterNamesResponse {
    
    private object returnField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public object @return {
        get {
            return this.returnField;
        }
        set {
            this.returnField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Servlet/")]
public partial class getInitParameterNames {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Servlet/")]
public partial class getServletConfigResponse {
    
    private object returnField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public object @return {
        get {
            return this.returnField;
        }
        set {
            this.returnField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Servlet/")]
public partial class getServletConfig {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Servlet/")]
public partial class logResponse {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Servlet/")]
public partial class log {
    
    private string msgField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string msg {
        get {
            return this.msgField;
        }
        set {
            this.msgField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Servlet/")]
public partial class getInitParameterResponse {
    
    private string returnField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string @return {
        get {
            return this.returnField;
        }
        set {
            this.returnField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Servlet/")]
public partial class getInitParameter {
    
    private string nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Servlet/")]
public partial class destroyBusResponse {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Servlet/")]
public partial class destroyBus {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Servlet/")]
public partial class serviceResponse {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Servlet/")]
public partial class service {
    
    private object reqField;
    
    private object resField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public object req {
        get {
            return this.reqField;
        }
        set {
            this.reqField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public object res {
        get {
            return this.resField;
        }
        set {
            this.resField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Servlet/")]
public partial class log1Response {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Servlet/")]
public partial class log1 {
    
    private string messageField;
    
    private object tField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string message {
        get {
            return this.messageField;
        }
        set {
            this.messageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public object t {
        get {
            return this.tField;
        }
        set {
            this.tField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Servlet/")]
public partial class init2Response {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Servlet/")]
public partial class init2 {
    
    private object scField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public object sc {
        get {
            return this.scField;
        }
        set {
            this.scField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Servlet/")]
public partial class setBusResponse {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Servlet/")]
public partial class setBus {
    
    private object busField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public object bus {
        get {
            return this.busField;
        }
        set {
            this.busField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Servlet/")]
public partial class getServletNameResponse {
    
    private string returnField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string @return {
        get {
            return this.returnField;
        }
        set {
            this.returnField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Servlet/")]
public partial class getServletName {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Servlet/")]
public partial class initResponse {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Servlet/")]
public partial class init {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Servlet/")]
public partial class init1Response {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Servlet/")]
public partial class init1 {
    
    private object filterConfigField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public object filterConfig {
        get {
            return this.filterConfigField;
        }
        set {
            this.filterConfigField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Servlet/")]
public partial class getServletContextResponse {
    
    private object returnField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public object @return {
        get {
            return this.returnField;
        }
        set {
            this.returnField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Servlet/")]
public partial class getServletContext {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Servlet/")]
public partial class getBusResponse {
    
    private object returnField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public object @return {
        get {
            return this.returnField;
        }
        set {
            this.returnField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Servlet/")]
public partial class getBus {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Servlet/")]
public partial class getServletInfoResponse {
    
    private string returnField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string @return {
        get {
            return this.returnField;
        }
        set {
            this.returnField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Servlet/")]
public partial class getServletInfo {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Servlet/")]
public partial class IOException {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Servlet/")]
public partial class ServletException {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void getServletInfoCompletedEventHandler(object sender, getServletInfoCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class getServletInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal getServletInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void getBusCompletedEventHandler(object sender, getBusCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class getBusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal getBusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public object Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((object)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void getServletContextCompletedEventHandler(object sender, getServletContextCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class getServletContextCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal getServletContextCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public object Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((object)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void init1CompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void initCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void getServletNameCompletedEventHandler(object sender, getServletNameCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class getServletNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal getServletNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void setBusCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void init2CompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void log1CompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void serviceCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void destroyBusCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void getInitParameterCompletedEventHandler(object sender, getInitParameterCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class getInitParameterCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal getInitParameterCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void logCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void getServletConfigCompletedEventHandler(object sender, getServletConfigCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class getServletConfigCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal getServletConfigCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public object Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((object)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void getInitParameterNamesCompletedEventHandler(object sender, getInitParameterNamesCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class getInitParameterNamesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal getInitParameterNamesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public object Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((object)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void doFilterCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void destroyCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
